# Generated by Django 3.2.4 on 2021-06-30 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brainstorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda', models.CharField(blank=True, max_length=255, null=True)),
                ('outcomes', models.CharField(blank=True, max_length=255, null=True)),
                ('decisions', models.CharField(blank=True, max_length=255, null=True)),
                ('pricing', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brainstorms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
