# Generated by Django 3.2.4 on 2021-07-04 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cubing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('different_idea', models.CharField(max_length=255)),
                ('described_idea', models.CharField(max_length=255)),
                ('compared_idea', models.CharField(max_length=255)),
                ('associate_idea', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cubing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
