# Generated by Django 3.2.4 on 2021-07-04 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cubing', '0002_auto_20210704_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubing',
            name='associate_idea',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cubing',
            name='compared_idea',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cubing',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cubing', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cubing',
            name='described_idea',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cubing',
            name='different_idea',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
