# Generated by Django 3.2.4 on 2021-07-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubing', '0004_auto_20210705_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubing',
            name='analyzed_idea',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cubing',
            name='applyed_idea',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cubing',
            name='argued_idea',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
