# Generated by Django 3.2.4 on 2021-07-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubing', '0005_auto_20210708_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubing',
            name='different_idea',
        ),
    ]
